apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-users-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: fake-users-api
        image: hsduiii\fake-users-api:latest
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: fake-users-api-entrypoint
  namespace: dev
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 8080